movies/urls.py
from django.urls import path, include

from movies import views

urlpatterns = [
    path('', views.MovieListView.as_view(), name='movies'),
    path('filter/', views.FilterMoviesView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('json-filter/', views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path('movie/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/add/', views.AddReviews.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
]

server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movies.urls')),
    path('subscribe/', include('subscribes.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]


admin.site.site_header = 'Movie Admin'              # default: "Django Administration"
admin.site.index_title = 'Movie Admin'              # default: "Site administration"
admin.site.site_title = 'Movie Admin'               # default: "Django site admin"

movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    Category
    """
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    class Meta:
        verbose_name = "Категория(-ю)"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        pass


class Actor(models.Model):
    """
    Actor
    """
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    class Meta:
        verbose_name = "Актеры и режисеры"
        verbose_name_plural = "Актеры и режисеры"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})


class Genre(models.Model):
    """
    Genre
    """
    name = models.CharField('Имя', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        pass


class Movie(models.Model):
    """
    Movie
    """
    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата выхода', default=2000)
    country = models.CharField('Страна', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='Режиcсер', related_name='film_directors')
    actors = models.ManyToManyField(Actor, verbose_name='Актеры', related_name='film_actors')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='Указать сумму в $')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='Указать сумму в $')
    fees_in_world = models.PositiveIntegerField('Сборы в мире', default=0, help_text='Указать сумму в $')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)


class MovieShots(models.Model):
    """
    MovieShots
    """
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        pass


class RatingStar(models.Model):
    """
    RatingStar
    """
    value = models.PositiveSmallIntegerField('Значение', default=0)

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ('-value',)

    def __str__(self):
        return str(self.value)

    def get_absolute_url(self):
        pass


class Rating(models.Model):
    """
    Rating
    """
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='Звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

    def __str__(self):
        return f'{self.star} - {self.movie}'

    def get_absolute_url(self):
        pass


class Reviews(models.Model):
    """
    Reviews
    """
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Родитель')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    def __str__(self):
        return f'{self.name} - {self.movie}'

    def get_absolute_url(self):
        pass

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from movies.models import Reviews, RatingStar, Rating


class ReviewForm(forms.ModelForm):
    """
    Форма отзывов
    """
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text', 'captcha')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control border'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control border'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control border'
            })
        }


class RatingForm(forms.ModelForm):
    """
    Форма добавления рейтинга
    """
    star = forms.ModelChoiceField(queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None)

    class Meta:
        model = Rating
        fields = ('star', )

movies/views.py
from django.db.models import Q, Avg
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView

from .forms import ReviewForm, RatingForm
from .models import Movie, Reviews, Actor, Genre, Rating


class GenreYear:
    """
    Жанры и года выхода фильмов
    """

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values('year')


class MovieListView(GenreYear, ListView):
    """
    Список фильмов
    """
    queryset = Movie.objects.filter(draft=False)
    template_name = 'movies/movie_list.html'
    context_object_name = 'movie_list'
    paginate_by = 5


class MovieDetailView(GenreYear, DetailView):
    """
    Детали о фильме
    """
    model = Movie
    template_name = 'movies/movie_detail.html'
    context_object_name = 'movie'
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        stars = self.get_user_stars(**self.kwargs)
        if stars:
            context['stars'] = str(stars)
        rating = Rating.objects.filter(movie_id=self.object.id).aggregate(average_rating=Avg('star__value'))
        if rating:
            context['average_rating'] = rating['average_rating']
        context['star_form'] = RatingForm()
        context['form'] = ReviewForm()
        return context

    def get_user_stars(self, **kwargs):
        ip = AddStarRating.get_client_ip(self, self.request)
        movie_id = Movie.objects.get(url=kwargs['slug']).id
        if Rating.objects.filter(ip=ip, movie_id=movie_id).exists():
            return Rating.objects.get(ip=ip, movie_id=movie_id).star
        else:
            return None


class AddReviews(CreateView):
    mode = Reviews
    form_class = ReviewForm

    def form_valid(self, form):
        movie = Movie.objects.get(pk=self.kwargs['pk'])
        instance = form.save(commit=False)
        if self.request.POST.get('parent', None):
            instance.parent_id = int(self.request.POST.get('parent'))
        instance.movie = movie
        instance.save()
        return HttpResponseRedirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = 'movies/actor_detail.html'
    slug_field = 'name'


class FilterMoviesView(GenreYear, ListView):
    """
    Фильтр фильмов
    """
    paginate_by = 5

    def get_queryset(self):
        qs = Movie.objects.filter(Q(year__in=self.request.GET.getlist('year')) |
                                  Q(genres__in=self.request.GET.getlist('genre')))\
            .distinct()
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['year'] = ''.join([f'year={x}&' for x in self.request.GET.getlist('year')])
        context['genre'] = ''.join([f'genre={x}&' for x in self.request.GET.getlist('genre')])
        return context


class JsonFilterMoviesView(ListView):
    """
    Фильтр фильмов в json
    """

    def get_queryset(self):
        qs = Movie.objects.filter(Q(year__in=self.request.GET.getlist('year')) |
                                  Q(genres__in=self.request.GET.getlist('genre')))\
            .distinct().values('title', 'tagline', 'url', 'poster')
        return qs

    def get(self, request, *args, **kwargs):
        qs = list(self.get_queryset())
        return JsonResponse({'movies': qs}, safe=False)


class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """ Поиск фильма """

    paginate_by = 5

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

movies/templates/movies/actor_detail.html
{% extends "movies/base.html" %}

{% block title %} {{ actor.name }} :: {{ block.super }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock %}

{% block breadcrumb %} {{ actor.name }} {% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ object.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ object.name }}</h3>
                <ul>
                    <li style="list-style: none"><span><b>Возраст:</b> {{ object.age }} лет</span></li>
                    <li style="list-style: none"><span><b>Режиссер:</b>
                        {% for movie in object.film_directors.all %}
                            <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                        {% endfor %}
                    </span></li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for movie in movie.film_actors.all %}
                            <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a>
                        {% endfor %}
                    </span></li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О {{ object.name }}</h3>
            <p class="editContent" style="outline: none; cursor: inherit;">
                {{ object.description | safe }}
            </p>
        </div>
    </div>
{% endblock %}

movies/templates/movies/base.html
{% extends 'base.html' %}

{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

movies/templates/movies/movie_detail.html
{% extends "movies/base.html" %}

{% block title %} {{ movie.title }} :: {{ block.super }} {% endblock %}

{% block container %}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock %}

{% block breadcrumb %} {{ movie.title }} {% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            {#            <div class="desc1-left col-md-6">#}
            <div class="col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}</h3>
                {#                <h5 class="editContent">Terminator: Dark Fate</h5>#}
                <ul>
                    <li style="list-style: none"><span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none"><span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none"><span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                            {% endfor %}
                        </span></li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                        {% endfor %}
                    </span></li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in movie.genre.all %}
                            {{ genre.name }}
                        {% endfor %}
                    </span></li>
                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.fees_in_world }}</span>
                    </li>
                    <li style="list-style: none">
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}" {% if stars == v %} checked {% endif %}>
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">{{ average_rating }}</span>
                        </form>
                    </li>
                </ul>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.title }}</h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.description | safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <div class="single-form-left col-md-9">
                    <div class="contact-single">
                        <h3 class="editContent">
                            <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>Оставить отзыв</h3>
                        <form action="{% url "add_review" movie.id %}" method="post" class="mt-4" id="formReview">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group editContent">
                                <label for="contactcomment" class="editContent">
                                    Ваш комментарий *
                                </label>
                                {{ form.text }}
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent">
                                    <label for="contactusername" class="editContent">
                                        Имя *
                                    </label>
                                    {{ form.name }}
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent">
                                    <label for="contactemail" class="editContent">
                                        Email *
                                    </label>
                                    {{ form.email }}
                                </div>
                                {{ form.captcha }}
                            </div>
                            <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                                Отправить
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                {% for review in movie.get_review %}
                    <div class="media py-5">
                        <img src="#" class="mr-3 img-fluid" alt="image">
                        <div class="media-body mt-4">
                            <h5 class="mt-0 editContent">{{ review.name }}</h5>
                            <p class="mt-2 editContent">
                                {{ review.text }}
                            </p>
                            <a href="#formReview"
                               onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                            {% for rev in review.reviews_set.all %}
                                <div class="media mt-5 editContent">
                                    <a class="pr-3" href="#">
                                        <img src="" class="img-fluid " alt="image">
                                    </a>
                                    <div class="media-body">
                                        <h5 class="mt-0 editContent">{{ rev.name }}</h5>
                                        <p class="mt-2 editContent">{{ rev.text }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById('contactparent').value = id
            document.getElementById('contactcomment').innerText = `${name}, `
        }
    </script>
{% endblock %}

movies/templates/movies/movie_list.html
{% extends "movies/base.html" %}

{% block title %} Movies :: {{ block.super }} {% endblock %}

{% block header %} bg1 {% endblock %}

{% block breadcrumb %}Movies{% endblock %}

{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">{{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock %}